env_variables:
  DATABASE_HOST: "${{ secrets.DATABASE_HOST }}"
  DATABASE_NAME: "u730606768_clientes"
  DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
  DATABASE_PORT: "3306"
  DATABASE_USER: "u730606768_grupo7"
  PORT: "3000"