service: cliente-service
frameworkVersion: "3"
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SERVICE_ACCOUNT: ${self:custom.secrets.service_account.SERVICE_ACCOUNT}

custom:
  bundle:
    tsConfig: "./tsconfig.json"
  serverless-offline-ssm:
    stages:
      - offline
  secrets:
    service_account: ${ssm:/aws/reference/secretsmanager/fiap}

functions:
  adiciona-cliente:
    handler: dist/handler.api
    events:
      - http:
          path: api/clientes/v1
          method: post
          cors: true
  atualiza-cliente:
    handler: dist/handler.api
    events:
      - http:
          path: api/clientes/v1/{cpf}
          method: put
          cors: true
  busca-cliente:
    handler: dist/handler.api
    events:
      - http:
          path: api/clientes/v1/{cpf}
          method: get
          cors: true
  autentica-cliente:
    handler: dist/handler.api
    events:
      - http:
          path: api/clientes/v1/autenticacao
          method: post
          cors: true
  busca-cliente-autenticado:
    handler: dist/handler.api
    events:
      - http:
          path: api/clientes/v1
          method: get
          cors: true
  health-check:
    handler: dist/handler.api
    events:
      - http:
          path: api/health-check/v1
          method: get
          cors: true

plugins:
  - serverless-offline-ssm
  - serverless-offline
