name: lambda-deployment-action

on: 
  push:
    branches:
      - main # You can use any of your root or master branch name
  
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          
      - name: Install serverless globally
        run: npm install -g serverless

      - name: Serverless login
        run: serverless login --token ${{ secrets.SERVERLESS_ACCESS_KEY }}
      
      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.MONGO_ATLAS_URI }}" >> .env
          echo "COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }}" >> .env
          echo "COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}" >> .env

      - name: Install npm dependencies
        run: npm i
     
      - name: Deploy lambda functions
        run: sls deploy