name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-verification:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: npm install
      
      - name: deploy to AWS Serverless
        run: npm run deploy:cliente:prod
